<?php

namespace App\Filament\Admin\Resources\BookingRequests\Tables;

use Filament\Actions\BulkActionGroup;
use Filament\Actions\DeleteBulkAction;
use Filament\Actions\EditAction;
use Filament\Actions\ForceDeleteBulkAction;
use Filament\Actions\RestoreBulkAction;
use Filament\Tables\Columns\IconColumn;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Filters\TrashedFilter;
use Filament\Tables\Table;

class BookingRequestsTable
{
    public static function configure(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make('client.id')
                    ->searchable(),
                TextColumn::make('bookable_type')
                    ->searchable(),
                TextColumn::make('bookable_id')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('tattoo_size')
                    ->searchable(),
                TextColumn::make('body_zone')
                    ->searchable(),
                TextColumn::make('estimated_price')
                    ->money()
                    ->sortable(),
                TextColumn::make('estimated_budget')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('preferred_timeframe')
                    ->badge(),
                TextColumn::make('preferred_date')
                    ->date()
                    ->sortable(),
                TextColumn::make('preferred_time_slot')
                    ->badge(),
                TextColumn::make('date_selection_deadline')
                    ->dateTime()
                    ->sortable(),
                TextColumn::make('client_dates_selected_at')
                    ->dateTime()
                    ->sortable(),
                TextColumn::make('confirmed_date')
                    ->date()
                    ->sortable(),
                TextColumn::make('confirmed_period')
                    ->searchable(),
                TextColumn::make('total_deposit_amount')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('deposit_amount')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('estimated_total_price')
                    ->money('EUR')
                    ->sortable(),
                TextColumn::make('price_estimate_min')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('price_estimate_max')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('client_payment_deadline_days')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('deposit_deadline_hours')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('tattooer_design_deadline_days')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('client_payment_deadline')
                    ->dateTime()
                    ->sortable(),
                TextColumn::make('tattooer_design_deadline')
                    ->dateTime()
                    ->sortable(),
                TextColumn::make('design_sent_at')
                    ->dateTime()
                    ->sortable(),
                TextColumn::make('deposit_deadline')
                    ->dateTime()
                    ->sortable(),
                IconColumn::make('is_long_term_booking')
                    ->boolean(),
                TextColumn::make('design_preparation_starts_at')
                    ->dateTime()
                    ->sortable(),
                IconColumn::make('design_preparation_notified')
                    ->boolean(),
                TextColumn::make('included_design_versions')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('included_designs')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('modifications_per_design')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('design_versions_used')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('designs_sent_count')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('current_design_modifications_count')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('stripe_payment_intent_id')
                    ->searchable(),
                TextColumn::make('status')
                    ->badge(),
                TextColumn::make('deposit_paid_at')
                    ->dateTime()
                    ->sortable(),
                TextColumn::make('expired_at')
                    ->dateTime()
                    ->sortable(),
                TextColumn::make('accepted_at')
                    ->dateTime()
                    ->sortable(),
                TextColumn::make('scheduled_start_time')
                    ->time()
                    ->sortable(),
                TextColumn::make('scheduled_end_time')
                    ->time()
                    ->sortable(),
                TextColumn::make('scheduled_duration_minutes')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('total_price')
                    ->money()
                    ->sortable(),
                TextColumn::make('balance_amount')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('balance_paid_at')
                    ->dateTime()
                    ->sortable(),
                TextColumn::make('balance_payment_method')
                    ->searchable(),
                TextColumn::make('balance_stripe_session_id')
                    ->searchable(),
                TextColumn::make('refund_amount')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('refund_percent')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('refund_processed_at')
                    ->dateTime()
                    ->sortable(),
                IconColumn::make('tattooer_missed_deadline')
                    ->boolean(),
                IconColumn::make('client_missed_deadline')
                    ->boolean(),
                TextColumn::make('appointment_datetime')
                    ->dateTime()
                    ->sortable(),
                TextColumn::make('appointment_duration_minutes')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('created_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                TextColumn::make('updated_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                TextColumn::make('deleted_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                TextColumn::make('overage_decision')
                    ->searchable(),
                TextColumn::make('surcharge_amount')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('surcharge_paid_at')
                    ->dateTime()
                    ->sortable(),
                TextColumn::make('cancelled_by')
                    ->searchable(),
                TextColumn::make('cancelled_at')
                    ->dateTime()
                    ->sortable(),
            ])
            ->filters([
                TrashedFilter::make(),
            ])
            ->recordActions([
                EditAction::make(),
            ])
            ->toolbarActions([
                BulkActionGroup::make([
                    DeleteBulkAction::make(),
                    ForceDeleteBulkAction::make(),
                    RestoreBulkAction::make(),
                ]),
            ]);
    }
}
